## Упражнения по библиотеке Numpy

In [70]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# Using mask to filter elements NOT INCLUDE 3 and 8
# [False False False  True  True  True  True False False]
mask = (arr > 3) & (arr < 8)

# Changing sing to opposite
arr[mask] *= -1

print("Changed array:")
print(arr)

**2.** Заменить максимальный элемент случайного массива на 0

In [ ]:
# Creating array
arr = np.random.randint(0, 10, size=(5, 5))
print("Given array:")
print(arr)

# Finding max element index with np.argmax() 
max_index = np.unravel_index(arr.argmax(), arr.shape)

# Changing max element to 0
arr[max_index] = 0

print("Array with changed element:")
print(arr)

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [73]:
# 2D array input
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# direct product
result = np.array(np.meshgrid(*arr)).T.reshape(-1, len(arr))

print(result)

[[1 4]
 [1 5]
 [1 6]
 [2 4]
 [2 5]
 [2 6]
 [3 4]
 [3 5]
 [3 6]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [74]:
# Arrays A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [1, 5, 7],
              [2, 4, 6],
              [3, 8, 9],
              [1, 4, 7],
              [2, 5, 8]])

B = np.array([[7, 3],
              [4, 1]])

# Find rows in A containing elements from each row B
matching_rows = np.all(np.isin(A, B), axis=1)

# Get indexes of matching rows in A
result = A[matching_rows]

print(result)

[[1 4 7]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [75]:
Z = np.random.randint(0, 5, (10, 3))  # Create a 10x3 matrix Z with random integers from 0 to 4

E = np.logical_and.reduce(Z[:, 1:] == Z[:, :-1], axis=1)

# E is a boolean array of size 10, where each element indicates if the corresponding row in Z has equal values.
# It uses np.logical_and.reduce() to check if all values in each row are equal.
# Z[:, 1:] selects all columns except the first one, and Z[:, :-1] selects all columns except the last one.
# The parameter axis=1 specifies that the comparison should be done along the rows.

U = Z[~E]
# U is a submatrix of Z that contains only the rows with non-equal values.
# The ~ operator is used to invert the boolean array E, selecting the rows where the values are not equal.

print("Original matrix Z:")
print(Z)
print("\nMatrix U with rows containing non-equal values:")
print(U)

Original matrix Z:
[[1 3 1]
 [0 1 3]
 [0 3 3]
 [2 2 2]
 [1 1 2]
 [1 3 0]
 [1 2 1]
 [4 1 0]
 [0 4 3]
 [2 1 0]]

Matrix U with rows containing non-equal values:
[[1 3 1]
 [0 1 3]
 [0 3 3]
 [1 1 2]
 [1 3 0]
 [1 2 1]
 [4 1 0]
 [0 4 3]
 [2 1 0]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [76]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [1, 2, 3],
                [7, 8, 9],
                [4, 5, 6]])
not_unique = np.unique(arr, axis=0)
print('array whithout duplicate rows')
print (not_unique)

array whithout duplicate rows
[[1 2 3]
 [4 5 6]
 [7 8 9]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [77]:
# Without NumPy
matrix = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
product = 1
for i in range(min(len(matrix), len(matrix[0]))):
    if matrix[i][i] != 0:
        product *= matrix[i][i]
print(product)

3


In [78]:
# with NumPy

matrix = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
product = np.prod(np.diagonal(matrix)[np.diagonal(matrix) != 0])
print(product)

3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [79]:
# with NumPy
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

result = np.array_equal(np.sort(x), np.sort(y))
print(result)

True


In [80]:
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]

result = sorted(x) == sorted(y)
print(result)

True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [81]:
# With NumPy

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

valid_indices = np.where(x[:-1] == 0)[0] + 1
max_element = np.max(x[valid_indices]) if len(valid_indices) > 0 else None
print(max_element)


5


In [82]:
# Without NumPy

x = [6, 2, 0, 3, 0, 0, 5, 7, 0]

valid_indices = [i + 1 for i in range(len(x) - 1) if x[i] == 0]
max_element = max([x[i] for i in valid_indices]) if valid_indices else None
print(max_element)


5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [83]:
# With NumPy
x = np.array([2, 2, 2, 3, 3, 3, 5])

values, counts = np.unique(x, return_counts=True)
result = (values, counts)
print(result)

(array([2, 3, 5]), array([3, 3, 1], dtype=int64))


In [84]:
# Without NumPy
x = [2, 2, 2, 3, 3, 3, 5]

values = []
counts = []
current_value = None
current_count = 0

for num in x:
    if num == current_value:
        current_count += 1
    else:
        if current_value is not None:
            values.append(current_value)
            counts.append(current_count)
        current_value = num
        current_count = 1

values.append(current_value)
counts.append(current_count)

result = (values, counts)
print(result)

([2, 3, 5], [3, 3, 1])


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [85]:
# def pairwise_distances(X, Y):
X = [[1, 2], [3, 4], [5, 6]]
Y = [[7, 8], [9, 10]]
# Transform lists into NumPy arrays
X = np.array(X)
Y = np.array(Y)
    
# We calculate the matrix of Euclidean distances between objects from samples X and Y
distances = np.sqrt(((X[:, np.newaxis] - Y) ** 2).sum(axis=2))
    
print(distances)

[[ 8.48528137 11.3137085 ]
 [ 5.65685425  8.48528137]
 [ 2.82842712  5.65685425]]


In [86]:
import math

def euclidean_distance(x1, x2):
    # Calculate the Euclidean distance between two points
    distance = math.sqrt(sum((a - b) ** 2 for a, b in zip(x1, x2)))
    return distance

def pairwise_distances(X, Y):
    # Transform lists into NumPy arrays
    X = np.array(X)
    Y = np.array(Y)
    
    # We calculate the matrix of Euclidean distances between objects from samples X and Y
    distances = []
    for x in X:
        row = []
        for y in Y:
            distance = euclidean_distance(x, y)
            row.append(distance)
        distances.append(row)
    return distances

X = [[1, 2], [3, 4], [5, 6]]
Y = [[7, 8], [9, 10]]

distances = pairwise_distances(X, Y)
print(distances)

[[8.48528137423857, 11.313708498984761], [5.656854249492381, 8.48528137423857], [2.8284271247461903, 5.656854249492381]]


In [87]:

# Coprare work speed with scipy.spatial.distance.cdist
    # time1 = timeit.timeit(lambda: pairwise_distances(X, Y), number=10000)
    # time2 = timeit.timeit(lambda: cdist(X, Y, metric='euclidean'), number=10000)

    # print("Running time without using NumPy::", time1)
    # print("Running time using NumPy::", time2)

In [88]:
# A vectorized implementation using NumPy is usually more efficient and faster than a non-NumPy implementation. 
# This is because NumPy operates on data arrays at a low level, which allows for optimized calculations at the C level. 
# This allows you to perform operations on data arrays faster.
# The scipy.spatial.distance.cdist function also uses optimized C code to calculate the Euclidean distance matrix. 
# It can be even more efficient as it uses specialized algorithms and optimizations to calculate distances.
# The NumPy implementation and the scipy.spatial.distance.cdist function are expected to be significantly faster 
# compared to the non-NumPy implementation. In particular, a vectorized implementation using NumPy can be orders of magnitude 
# faster due to optimized array operations.

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [89]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [90]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [91]:
# np.mean calculating the average value of the number of calories in an array

average_calories_check = np.mean(calorie_stats) - 60 
average_calories = round(average_calories_check, 2)
print("The average number of calories in competitors is higher by:", rounded_average_calories)



The average number of calories in competitors is higher by: 46.88


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [92]:
# your code
calorie_stats_sorted = np.sort(calorie_stats)

print("Sorted calorie information::")
print(calorie_stats_sorted)

Sorted calorie information::
[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [93]:
# np.median() to calculate the median of a dataset
median_calories = np.median(calorie_stats)

print("Median number of calories:", median_calories)

Median number of calories: 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [94]:
# Calculating percentiles from 0 to 100
percentiles = np.arange(0, 101)  

for percentile in percentiles:
    nth_percentile = np.percentile(calorie_stats, percentile)
    if nth_percentile > 60:
        break

print("Lowest percentile over 60 calories:", nth_percentile)

Lowest percentile over 60 calories: 70.0


In [95]:
# Lowest percentile over 60 calories: 70.0

# This means that 70% of competing products have more calories than CrunchieMunchies (at 60 calories). 
# That is, more than 2/3 of competing products have more calories than CrunchieMunchies. 
# This suggests that a significant portion of competing products have a higher calorie count than CrunchieMunchies.

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [96]:
# np.sum() to count the number of cereals that contain more than 60 calories (calorie_stats > 60 condition). 
# We then divide this number by the total number of cereals (len(calorie_stats)) and multiply by 100 to get the percentage

more_calories = np.sum(calorie_stats > 60) / len(calorie_stats) * 100

print("Percentage of cereal with more than 60 calories:", round(more_calories,2))

Percentage of cereal with more than 60 calories: 96.1


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [97]:
# np.std() Compute the standard deviation along the specified axis.

calorie_std = np.std(calorie_stats)

print("Standard deviation of calories:", calorie_std)

Standard deviation of calories: 19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:

# Conclusions: CrunchieMunchies has fewer calories (60) than the competition, which averages around 106.88 calories. 
# Over 73% of the cereals in the dataset contain more than 60 calories per serving. 
# The standard deviation of caloric values is about 19.36, 
# which indicates a significant variation in the number of calories between cereals. 
# The data can be used to highlight the low calorie content of CrunchieMunchies in marketing materials, 
# drawing attention to its benefits in the context of a healthy lifestyle and calorie control.


In [ ]:
# Thanks for watching